const fotos = require('../routes/kids/fotos');

const pessoas =
[{
    "id": 1020,
    "oi" : {"value": "10."},
    "nome": "João Paulo Pedro Barbosa",
    "apelido": "Joãozinho",
    "alergias": "Amendoim",
    "sexo": "MASCULINO",
    "dataNascimento": "2016-11-16T19:35:21.056Z",
    "saude": "Muito boa",
    "observacao": "Medo de Palhaço",
    "origem": "APP_KIDS_PAIS",
    "type": "PessoaPre",
    "responsavel": false,
    "fotoBase64": fotos.boy,
  },
  {
    "id": 1021,
    "oi" : {"value": "10."},
    "nome": "Agatha Evelyn Castro Barbosa",
    "apelido": "Eve",
    "alergias": "Nenhuma",
    "sexo": "MASCULINO",
    "dataNascimento": "1999-12-25T19:35:21.056Z",
    "saude": "Tem rinite",
    "observacao": "Come cola se deixar",
    "origem": "APP_KIDS_PAIS",
    "type": "PessoaPre",
    "responsavel": false,
    "fotoBase64": fotos.girl
  },
  {
    "id": 1019,
    "oi" : {"value": "10."},
    "nome": "Cavalo Filipe Diogo Rodrigues Barbosa",
    "apelido": "Felipão",
    "sexo": "MASCULINO",
    "dataNascimento": "1979-12-25T19:35:21.056Z",
    "email": "fdb@email.com",
    "estadoCivil": "Casado",
    "cpf": "63424386090",
    "cep": "60511746",
    "uf": "Pr",
    "cidade": "Maringá",
    "bairro": "Zona 7",
    "numero": "123",
    "complemento": "Proximo a UEM",
    "logradouro": "Um Logradouro Qualquer",
    "origem": "APP_KIDS_PAIS",
    "type": "PessoaPre",
    "responsavel": true,
    "fotoBase64": fotos.man
  },
  {
    "id": 1022,
    "oi" : {"value": "10."},
    "nome": "Mariana Hadassa Barbosa",
    "apelido": "Mari",
    "sexo": "FEMININO",
    "dataNascimento": "1985-10-12T19:35:21.056Z",
    "email": "maribarbosa@email.com",
    "estadoCivil": "Casado",
    "cpf": "96595216930",
    "cep": "59092310",
    "uf": "Pr",
    "cidade": "Maringá",
    "bairro": "Zona 7",
    "numero": "123",
    "complemento": "Proximo a UEM",
    "logradouro": "Um Logradouro Qualquer",
    "origem": "APP_KIDS_PAIS",
    "type": "PessoaPre",
    "responsavel": true,
    "fotoBase64": fotos.woman
  },
  {
    "id": 1023,
    "oi" : {"value": "10."},
    "nome": "Marina Olivia Beatriz Gomes Barbosa",
    "apelido": "Marina",
    "sexo": "FEMININO",
    "dataNascimento": "1985-10-12T19:35:21.056Z",
    "email": "merinaolbarbosa@email.com",
    "estadoCivil": "Viuva",
    "cpf": "25901203461",
    "cep": "49001252",
    "uf": "Pr",
    "cidade": "Maringá",
    "bairro": "Zona 7",
    "numero": "123",
    "complemento": "Proximo a UEM",
    "logradouro": "Um Logradouro Qualquer",
    "origem": "APP_KIDS_PAIS",
    "type": "PessoaPre",
    "responsavel": true,
    "fotoBase64": fotos.oldwoman
  }
]

module.exports = pessoas;
